{{- if and .Values.dispatcher.customUrls.enabled .Values.dispatcher.customUrls.domains }}
apiVersion: v1
kind: Secret
metadata:
  name: dispatcher-custom-urls-secret
  labels:
    app: dispatcher
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range .Values.dispatcher.customUrls.domains }}
{{- $tenantNormalized := .tenant | lower | replace "." "_" | replace "-" "_" }}
{{- $domainNormalized := .domain | lower | replace "." "_" | replace "-" "__" }}
{{- if .certFile }}
  {{ $tenantNormalized }}_{{ $domainNormalized }}_cert: {{ .certFile | b64enc | b64enc | quote }}
{{- end }}
{{- if .keyFile }}
  {{ $tenantNormalized }}_{{ $domainNormalized }}_key: {{ .keyFile | b64enc | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
