apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
  labels:
    app: dispatcher
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  NSS_SDB_USE_CACHE: "no"
  PORTAL_SUBDOMAIN: {{ required "Please fill in domain in values.yaml" .Values.portal.domain | quote }}
  PORTAL_VERSION: {{ .Chart.AppVersion | quote }}
  TSSG_PUBLIC_HOST: {{ include "tssg-public-host" . | quote }}
  USE_PROXY_PROTOCOL: "false"
{{ if .Values.dispatcher.additionalEnv }}
{{- range $key, $val := .Values.dispatcher.additionalEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{ end }}
