apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"portal-https":"HTTPS"}'
  labels:
    app: dispatcher
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      name: portal-https
    - port: 9443
      targetPort: 9443
      name: pass-through
  selector:
    app: dispatcher
  type: ClusterIP
  sessionAffinity: ClientIP