{{if or (not .Values.ingress.existingSecret) (.Values.tls.saas)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secretName }}
  labels:
    app: dispatcher
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
{{ if .Values.tls.saas }}
  tls.crt: {{ .Values.tls.external.dispatcherssl.crt | quote }}
  tls.key: {{ .Values.tls.external.dispatcherssl.key | quote }}
{{ else }}
{{ if not .Values.tls.useSignedCertificates}}
{{ ( include "dispatcher-self-signed" . ) | indent 2 }}
{{ else }}
  tls.crt: {{ include "dispatcher-ssl-crt" . | b64enc | quote }}
  tls.key: {{ include "dispatcher-ssl-key" . | b64enc | quote }}
{{ end }}
{{ end }}
{{ end }}
