{{- if .Values.portal.intelligence.enabled }}
{{- if and .Values.intelligence.serviceAccount.create (not .Values.global.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "intelligence.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: intelligence-server
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
automountServiceAccountToken: {{ .Values.intelligence.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
