{{- if and .Values.intelligenceServer.s3.enabled (not .Values.intelligenceServer.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intelligence.fullname" . }}-s3-secret
  labels:
    app: intelligence-server
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.intelligenceServer.s3.accessKey }}
  access-key: {{ .Values.intelligenceServer.s3.accessKey | b64enc | quote }}
  {{- else }}
  access-key: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.intelligenceServer.s3.secretKey }}
  secret-key: {{ .Values.intelligenceServer.s3.secretKey | b64enc | quote }}
  {{- else }}
  secret-key: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}
