apiVersion: v1
kind: Service
metadata:
  name: intelligence-server
  labels:
    app: intelligence-server
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.intelligenceServer.service.type }}
  ports:
    - name: http
      port: {{ .Values.intelligenceServer.service.port }}
      targetPort: 8282
  selector:
    app: intelligence-server
    release: {{ .Release.Name }}
  {{- if .Values.intelligenceServer.service.sessionAffinity }}
  sessionAffinity: {{ .Values.intelligenceServer.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.intelligenceServer.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- toYaml .Values.intelligenceServer.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.intelligenceServer.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.intelligenceServer.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.intelligenceServer.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.intelligenceServer.service.internalTrafficPolicy }}
  {{- end }}