apiVersion: v1
kind: Secret
metadata:
  name: intelligence-server-secret
  labels:
    app: intelligence-server
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}
  MONGO_DB_USERNAME: {{ required "Please fill in mongodb.auth.username  in values.yaml" .Values.mongodb.auth.username | b64enc | quote }}