apiVersion: v1
kind: Service
metadata:
  name: intelligence-server
  labels:
    app: intelligence-server
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: "8282"
      port: {{ .Values.intelligenceServer.port }}
      targetPort: 8282
  selector:
    app: intelligence-server
  sessionAffinity: ClientIP