# Copyright (c) 2026 Broadcom Inc. and its subsidiaries. All Rights Reserved.
{{- if .Values.database.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gateway.fullname" . }}-db-migration
  annotations:
    chartversion: {{ .Chart.AppVersion | quote }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": {{ .Values.database.migrationJob.hookWeight | quote }}
    {{- if .Values.database.migrationJob.annotations }}
    {{- range $key, $val := .Values.database.migrationJob.annotations }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- end }}
  labels:
    app: {{ template "gateway.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ template "gateway.fullname" . }}-db-migration
        release: {{ .Release.Name }}
      {{- if .Values.database.migrationJob.podAnnotations }}
      annotations: {{- toYaml .Values.database.migrationJob.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ template "gateway.imagePullSecret" . }}
      {{- end }}
      containers:
        - name: db-migration
          image: {{.Values.image.registry}}/{{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "gateway.fullname" . }}-configmap
            - secretRef:
                name: {{ template "gateway.secretName" . }}
          env:
            - name: SSG_DATABASE_JDBC_URL
              value: {{ required "A direct primary database JDBC URL (database.migrationJob.jdbcUrl) is REQUIRED when the migration job is enabled to bypass proxies." .Values.database.migrationJob.jdbcUrl | quote }}
            - name: EXTRA_JAVA_ARGS
              value: "-Dgateway.db.schema-update.mode=liquibase-only
          volumeMounts:
            - name: {{ template "gateway.fullname" . }}-license-xml
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
              subPath: license.xml
            {{- if (not .Values.disklessConfig.enabled) }}
            {{- if (not .Values.disklessConfig.setSecretByInitContainer) }}
            - name: {{ template "gateway.fullname" . }}-node-properties
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/conf/node.properties
              subPath: node.properties
            {{- else }}
            - name: shared-secret
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/conf/node.properties
              subPath: node.properties
            {{- end }}
            {{- end }}
      volumes:
        - name: {{ template "gateway.fullname" . }}-license-xml
          secret:
            secretName: {{ template "gateway.license" . }}
            items:
            - key: license
              path: license.xml
      {{- if and (not .Values.disklessConfig.enabled) (not .Values.disklessConfig.setSecretByInitContainer) }}
        - name: {{ template "gateway.fullname" . }}-node-properties
          {{- if .Values.disklessConfig.existingSecret.csi }}
          csi: {{ toYaml .Values.disklessConfig.existingSecret.csi | nindent 12 }}
          {{- else }}
          secret:
            secretName: {{ template "gateway.node.properties" . }}
            items:
            - key: node.properties
              path: node.properties
          {{- end }}
      {{- end }}
      restartPolicy: "Never"
{{- end }}