{{- if .Values.config.gemfire  }}
{{- if or (.Values.config.gemfire.external.auth.enabled) (.Values.config.gemfire.external.ssl.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-ext-gemfire-security-properties
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
stringData:
  gemfire_security: |+
    {{- if (.Values.config.gemfire.external.ssl.enabled) }}
    ssl-keystore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/ExternalGemfireSharedStateProviderAssertion/gemfire-keystore
    ssl-keystore-password={{ .Values.config.gemfire.external.ssl.keystorePassword }}
    ssl-truststore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/ExternalGemfireSharedStateProviderAssertion/gemfire-truststore
    ssl-truststore-password={{ .Values.config.gemfire.external.ssl.truststorePassword }}
{{ .Values.config.gemfire.external.ssl.additionalProperties | indent 4 }}
    {{- end }}
    {{- if (.Values.config.gemfire.external.auth.enabled)}}
    security-username={{ .Values.config.gemfire.external.auth.username }}
    security-password={{ .Values.config.gemfire.external.auth.password }}
    {{- end }}
{{- end }}
{{- end }}