{{- if and (.Values.config.gemfire) (.Values.config.gemfire.ssl.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-gemfire-certs
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
data:
  truststore: {{ .Values.config.gemfire.ssl.truststore | b64enc }}
  keystore: {{ .Values.config.gemfire.ssl.keystore | b64enc }}
{{- end }}