{{ if .Values.ingress.enabled }}
{{- $kubeTargetVersion := .Capabilities.KubeVersion.GitVersion }}
{{- if semverCompare ">=1.19-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
 name: {{ template "gateway.fullname" . }}-ingress
 labels:
   chart: {{ template "gateway.chart" . }}
   release: {{ .Release.Name }}
   heritage: {{ .Release.Service }}
 annotations:
{{- range $key, $val := .Values.ingress.annotations }}
   {{ $key }}: "{{ $val }}"
{{- end }}
spec:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  tls:
{{ toYaml .Values.ingress.tls | indent 2 }}
  rules:
{{- $gatewayFullName := include "gateway.fullname" . }}
{{- range .Values.ingress.rules }}
  - host: {{ .host }}
    http:
      paths:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
      - pathType: Prefix
        path: {{ .path }}
        backend:
          service:
            name: {{ $gatewayFullName }}
            port:
            {{- if .service.port.number }}
              number: {{ .service.port.number }}
            {{- else }}
              name: {{ .service.port.name }}
            {{- end }}
{{- else }}
      - backend:
          serviceName: {{ template "gateway.fullname" . }}
          servicePort: {{ .service.port.number }}
{{- end }}
{{- end }}
{{ end }}
