{{ if .Values.ingress.enabled }}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
 name: {{ template "gateway.fullname" . }}-ingress
 labels:
   chart: {{ template "gateway.chart" . }}
   release: {{ .Release.Name }}
   heritage: {{ .Release.Service }}
   {{- range $key, $val := .Values.additionalLabels }}
   {{ $key }}: "{{ $val }}"
   {{- end }}
 annotations:
{{- range $key, $val := .Values.ingress.annotations }}
   {{ $key }}: "{{ $val }}"
{{- end }}
spec:
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  tls:
{{ toYaml .Values.ingress.tls | indent 2 }}
  rules:
{{- $gatewayFullName := include "gateway.fullname" . }}
{{- range .Values.ingress.rules }}
  - host: {{ .host }}
    http:
      paths:
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
      - pathType: Prefix
        path: {{ .path }}
        backend:
          service:
           {{- if .backend }}
           {{- if eq .backend "management" }}
            name: {{ $gatewayFullName }}-management
           {{- else }}
            name: {{ $gatewayFullName }}
           {{- end }}
           {{- else }}
            name: {{ $gatewayFullName }}
           {{- end }}
            port:
            {{- if .service.port.number }}
              number: {{ .service.port.number }}
            {{- else }}
              name: {{ .service.port.name }}
            {{- end }}
{{- else }}
      - backend:
          serviceName: {{ template "gateway.fullname" . }}
          servicePort: {{ .service.port.number }}
{{- end }}
{{- end }}
{{ end }}
