{{ if not .Values.license.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.license" . }}
  annotations:
    description: Template for Secrets for the Gateway license
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
type: Opaque
data:
  license: {{ required "Please provide a Layer7 Gateway license, if you aren't sure contact your Broadcom Sales Representative" .Values.license.value | b64enc | quote }}
{{ end }}
