{{ if and (.Values.management.restman.enabled) (.Values.otk.enabled) (.Values.otk.database.readOnlyConnection.enabled) (not .Values.otk.database.readOnlyConnection.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "otk.dbSecretName.readOnly" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- if  .Values.additionalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
data:
  OTK_RO_DATABASE_PASSWORD : {{ required "Please fill in otk.database.readOnlyConnection.password in values.yaml" .Values.otk.database.readOnlyConnection.password | b64enc }}
  OTK_RO_DATABASE_USERNAME : {{ required "Please fill in otk.database.readOnlyConnection.username in values.yaml" .Values.otk.database.readOnlyConnection.username| b64enc }}
{{ end }}