{{ if .Values.pmtagger.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}-pm-tagger-configmap
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    version: {{ .Values.pmtagger.image.tag }}
    namespace: {{ .Release.Namespace }}
    labels:
      app: {{ template "gateway.fullname" . }}
      release: {{ .Release.Name }}
{{ end }}