apiVersion: v1
kind: Service
metadata:
  name: ingestion-server
  labels:
    app: ingestion-server
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 9042
      targetPort: 9042
      name: {{ .Values.ingestion.portName }}
  selector:
    app: ingestion-server
  type: ClusterIP
  sessionAffinity: ClientIP