apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: solr
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8983
  selector:
    app: solr
  type: ClusterIP