
# Global values
global:
  portalRepository: caapim/
  pullSecret: broadcom-apim
  databaseType: mysql
  databaseHost: mysql
  databasePort: 3306
  databaseUseSSL: true
  databaseRequireSSL: false
  databaseUsername: portal
  databaseSecret: database-secret
  subdomainPrefix: dev-portal
  legacyHostnames: false
  legacyDatabaseNames: false
  setupDemoDatabase: true
  intelligence:
    enabled: true
# databasePassword: 7layer

  imageRegistry: ""
  imagePullSecrets:
    - broadcom-apim
  defaultStorageClass: ""
  storageClass: ""

forceRedeploy: false
standalone: false

serviceAccount:
  create: true

# Valid only if standalone is true
intelligence:
  useExistingPullSecret: false
  registryCredentials:
  # Set this if you would like to add an image pull secret directly to the Portal deployment.
  imagePullSecret:
    enabled: false
    username:
    password:

image:
  intelligenceServer: intelligence-server:develop

security: 
  mongodb:
    useExistingSectet: false
    secretName: mongodb-secret
    rootPassword: password
    dbPassword: 7layer

kafka:
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
      name: CLIENT
      sslClientAuth: ""
    controller:
      name: CONTROLLER
      containerPort: 9093
      protocol: SASL_PLAINTEXT
      sslClientAuth: ""
    interbroker:
      containerPort: 9094
      protocol: SASL_PLAINTEXT
      name: INTERNAL
      sslClientAuth: ""
    external:
      containerPort: 9095
      protocol: SASL_PLAINTEXT
      name: EXTERNAL
      sslClientAuth: ""

mongodb:
  useStatefulSet: true
  architecture: standalone
  containerPorts:
    mongodb: 27017
  auth:
    enabled: true
    rootUser: root
    username: portal
    database: intelligence
    existingSecret: mongodb-secret


intelligenceServer:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  resources:
    requests: {}
    limits: {}
  service:
    port: 8282
    type: ClusterIP



# We recommend that MySQL is externalised, the default implementation here is for reference only and is NOT suitable for use
# in any production environment.
# MySQL Stable Chart values - https://github.com/bitnami/charts/tree/master/bitnami/mysql
mysql:
  image:
    tag: "8.0.37-debian-12-r2"
  auth:
    username: portal
    existingSecret: database-secret
  # primary:
  #   podSecurityContext:
  #     enabled: true
  #     fsGroup: 100
  #   containerSecurityContext:
  #     enabled: true
  #     runAsUser: 1001
  initdbScripts:
    elevate-admin.sql: |
      GRANT ALL PRIVILEGES ON *.* TO 'portal'@'%'; FLUSH PRIVILEGES;
  primary:
    configuration: |-
      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=utf8mb4
      plugin_dir=/opt/bitnami/mysql/plugin
      [mysqld]
      default_authentication_plugin=mysql_native_password
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      collation-server=utf8mb4_0900_ai_ci
      character-set-server=utf8mb4
      innodb_log_buffer_size=32M
      innodb_log_file_size=80M
      max_allowed_packet=8M
      group_concat_max_len=512000
      sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    pdb:
      create: false
      maxUnavailable: ""
      minAvailable: ""
    persistence:
      annotations:
        helm.sh/hook: pre-install
        helm.sh/hook-weight: "-10"
  commonAnnotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"