apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  clusterIP: None
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}

