apiVersion: v1
kind: Secret
metadata:
  name: {{ template "portal.fullname" . }}-job-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  P12_INTERNAL_PASS: {{ randAlphaNum 15 | b64enc | quote }}
  P12_EXTERNAL_PASS: {{ randAlphaNum 15 | b64enc | quote }}
{{ if .Values.tls.useSignedCertificates }}
  CRT: {{ required "tls.useSignedCertificates is true - please set tls.crt via --set-file or in values.yaml" .Values.tls.crt | b64enc | b64enc | quote }}
  CRTCHAIN: {{ required "tls.useSignedCertificates is true - please set tls.certChain via --set-file or in values.yaml" .Values.tls.crtChain | b64enc | b64enc | quote }}
  PRIV_KEY: {{ required "tls.useSignedCertificates is true - please set tls.key via --set-file or in values.yaml" .Values.tls.key | b64enc | b64enc | quote }}
  PRIV_KEY_PASS: {{ default "" .Values.tls.keyPass | b64enc | quote }}
{{ end }}
  INTERNAL_SECRETNAME: {{.Values.tls.internalSecretName | b64enc | quote }}
  EXTERNAL_SECRETNAME: {{.Values.tls.externalSecretName | b64enc | quote }}