apiVersion: v1
kind: Secret
metadata:
  name: apim-secret
  labels:
    app: apim
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | b64enc | quote }}