apiVersion: v1
kind: Service
metadata:
  name: historical
  labels:
    app: historical
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: historical
  sessionAffinity: ClientIP