{{- if and .Values.serviceAccount.create (not .Values.global.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portal.serviceAccountName" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-9"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
secrets:
  - name: {{ include "portal.fullname" . }}
{{- end }}