apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: coordinator
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: "8081"
    port: {{ .Values.coordinator.port }}
    targetPort: 8081
  selector:
    app: coordinator
  sessionAffinity: ClientIP