apiVersion: v1
kind: Service
metadata:
  name: authenticator
  labels:
    app: authenticator
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 9081
      targetPort: 9081
      name: auth-http
  selector:
    app: authenticator
  type: ClusterIP
  sessionAffinity: ClientIP
