# Copyright (c) 2026 Broadcom Inc. and its subsidiaries. All Rights Reserved.
# AI assistance has been used to generate some or all contents of this file. That includes, but is not limited to, new code, modifying existing code, stylistic edits.
apiVersion: v1
kind: Service
metadata:
  name: authenticator
  labels:
    app: authenticator
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 9081
      targetPort: 9081
      name: auth-http
    - port: 8081
      targetPort: 8081
      name: rbac-http
  selector:
    app: authenticator
  type: ClusterIP
  sessionAffinity: ClientIP
