apiVersion: v1
kind: Secret
metadata:
  name: authenticator-secret
  labels:
    app: authenticator
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}  
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
{{ if .Values.authenticator.additionalSecret }}
{{- range $key, $val := .Values.authenticator.additionalSecret }}
  {{ $key }}: {{ $val | toString | b64enc }}
{{- end }}
{{ end }}