apiVersion: v2
name: kafka
description: Apache Kafka Chart for Broadcom APIM
type: application
home: https://github.com/CAAPIM/apim-charts
maintainers:
  - name: Gazza7205
sources:
  - https://github.com/CAAPIM/apim-charts
version: 1.2.4
appVersion: 5.4

