apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.portal.papi.secretName}}
  annotations:
    helm.sh/hook: pre-install
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  papi-username: {{ "papi" | b64enc | quote }}
{{if .Values.portal.papi.password }}
  papi-password: {{ .Values.portal.papi.password | b64enc | quote }}
{{ else }}
  papi-password: {{ randAlphaNum 16 | b64enc | quote }}
{{ end }}