apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.portal.internalSSG.secretName}}
  annotations:
    helm.sh/hook: pre-install
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{if .Values.portal.internalSSG.username }}
  internal-ssg-username: {{ .Values.portal.internalSSG.username | b64enc | quote }}
{{ else }}
  internal-ssg-username: {{ randAlpha 10 | b64enc | quote }}
{{ end }}
{{if .Values.portal.internalSSG.password }}
  internal-ssg-password: {{ .Values.portal.internalSSG.password | b64enc | quote }}
{{ else }}
  internal-ssg-password: {{ randAlphaNum 28 | b64enc | quote }}
{{ end }}