{{- if and .Values.intelligenceServer.rbac.create .Values.intelligenceServer.serviceAccount.create (not .Values.global.serviceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "intelligence.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "intelligence.name" . }}
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "intelligence.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "intelligence.serviceAccountName" . }}
{{- end }}