{{- if and .Values.serviceAccount.create (not .Values.global.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "intelligence.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "intelligence.name" . }}
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
secrets:
  - name: {{ include "intelligence.fullname" . }}
{{- end }}