apiVersion: v1
kind: Service
metadata:
  name: middlemanager
  labels:
    app: middlemanager
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: "8091"
    port: 8091
    targetPort:  8091
  selector:
    app: middlemanager
  sessionAffinity: ClientIP