apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: seaweedfs
    component: master
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"    
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: "swfs-master"
    port: {{ .Values.master.port }}
    targetPort: {{ .Values.master.port }}
    protocol: TCP
  - name: "swfs-master-grpc"
    port: {{ .Values.master.grpcPort }}
    targetPort: {{ .Values.master.grpcPort }}
    protocol: TCP
  selector:
    app: seaweedfs
    component: master
