{{- if .Values.master.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: seaweedfs
    chart: {{ template "druid.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: seaweedfs-master
  podManagementPolicy: Parallel
  replicas: {{ .Values.master.replicas }}
  {{- if (gt (int .Values.master.updatePartition) 0) }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: {{ .Values.master.updatePartition }}
  {{- end }}
  selector:
    matchLabels:
      app: seaweedfs
      chart: {{ template "druid.name" . }}
      release: {{ .Release.Name }}
      component: master
  template:
    metadata:
      labels:
        app: seaweedfs
        chart: {{ template "druid.name" . }}
        release: {{ .Release.Name }}
        component: master
    spec:
      restartPolicy: Always
      {{- if .Values.master.affinity }}
      affinity:
        {{ tpl .Values.master.affinity . | nindent 8 | trim }}
      {{- end }}
      {{- if .Values.master.tolerations }}
      tolerations:
        {{ tpl .Values.master.tolerations . | nindent 8 | trim }}
      {{- end }}
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      {{- if .Values.master.priorityClassName }}
      priorityClassName: {{ .Values.master.priorityClassName | quote }}
      {{- end }}
      enableServiceLinks: false
      containers:
        - name: seaweedfs
          image: {{ template "master.image" . }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.global.imagePullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SEAWEEDFS_FULLNAME
              value: "seaweedfs"
            {{- if .Values.master.extraEnvironmentVars }}
            {{- range $key, $value := .Values.master.extraEnvironmentVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.global.extraEnvironmentVars }}
            {{- range $key, $value := .Values.global.extraEnvironmentVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          command:
            - "/bin/sh"
            - "-ec"
            - | 
              exec /usr/bin/weed -logdir=/logs \
              {{- if .Values.master.loggingOverrideLevel }}
              -v={{ .Values.master.loggingOverrideLevel }} \
              {{- else }}
              -v={{ .Values.global.loggingLevel }} \
              {{- end }}
              master \
              -port={{ .Values.master.port }} \
              -mdir=/data \
              -ip.bind={{ .Values.master.ipBind }} \
              {{- if .Values.global.enableReplication }}
              -defaultReplication={{ .Values.global.replicationPlacment }} \
              {{- else }}
              -defaultReplication={{ .Values.master.defaultReplication }} \
              {{- end }}
              {{- if .Values.master.volumePreallocate }}
              -volumePreallocate \
              {{- end }}
              -volumeSizeLimitMB={{ .Values.master.volumeSizeLimitMB }} \
              {{- if .Values.master.disableHttp }}
              -disableHttp \
              {{- end }}
              {{- if .Values.master.pulseSeconds }}
              -pulseSeconds={{ .Values.master.pulseSeconds }} \
              {{- end }}
              {{- if .Values.master.garbageThreshold }}
              -garbageThreshold={{ .Values.master.garbageThreshold }} \
              {{- end }}
              {{- if .Values.master.metricsIntervalSec }}
              -metrics.intervalSeconds={{ .Values.master.metricsIntervalSec }} \
              {{- end }}
              -ip=${POD_NAME}.${SEAWEEDFS_FULLNAME}-master \
              -peers={{ range $index := until (.Values.master.replicas | int) }}${SEAWEEDFS_FULLNAME}-master-{{ $index }}.${SEAWEEDFS_FULLNAME}-master:{{ $.Values.master.port }}{{ if lt $index (sub ($.Values.master.replicas | int) 1) }},{{ end }}{{ end }}
          volumeMounts:
            - name : data-{{ .Release.Namespace }}
              mountPath: /data
            - name: seaweedfs-master-log-volume
              mountPath: "/logs/"            
            {{ tpl .Values.master.extraVolumeMounts . | nindent 12 | trim }}
          ports:
            - containerPort: {{ .Values.master.port }}
              name: swfs-master
            - containerPort: {{ .Values.master.grpcPort }}
              #name: swfs-master-grpc
          readinessProbe:
            httpGet:
              path: /cluster/status
              port: {{ .Values.master.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 45
            successThreshold: 2
            failureThreshold: 100
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /cluster/status
              port: {{ .Values.master.port }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 10
          {{- if .Values.master.resources }}
          resources:
            {{ tpl .Values.master.resources . | nindent 12 | trim }}
          {{- end }}
      volumes:
        - name: seaweedfs-master-log-volume
          hostPath:
            path: /storage/logs/seaweedfs/master
            type: DirectoryOrCreate
        - name: data-{{ .Release.Namespace }}
          hostPath:
            path: /ssd/seaweed-master/
            type: DirectoryOrCreate        
        {{ tpl .Values.master.extraVolumes . | indent 8 | trim }}
      {{- if .Values.master.nodeSelector }}
      nodeSelector:
        {{ tpl .Values.master.nodeSelector . | indent 8 | trim }}
      {{- end }}
{{/*  volumeClaimTemplates:*/}}
{{/*    - metadata:*/}}
{{/*        name: data-{{ .Release.Namespace }}*/}}
{{/*      spec:*/}}
{{/*        accessModes:*/}}
{{/*          - ReadWriteOnce*/}}
{{/*        resources:*/}}
{{/*          requests:*/}}
{{/*            storage: {{ .Values.master.storage }}*/}}
{{/*        {{- if .Values.master.storageClass }}*/}}
{{/*        storageClassName: {{ .Values.master.storageClass }}*/}}
{{/*        {{- end }}*/}}
{{- end }}
