{{- if or (.Values.config.gemfire.embedded.auth.enabled) (.Values.config.gemfire.embedded.tls.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-emb-gemfire-security-properties
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
  {{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
type: Opaque
stringData:
  gfsecurity.properties: |+
    {{- if (.Values.config.gemfire.embedded.tls.enabled) }}
    ssl-keystore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/keystore.p12
    {{- if .Values.config.gemfire.embedded.tls.existingSecret }}
    ssl-keystore-password={{ .Values.config.gemfire.embedded.tls.password }}
    {{- else }}
    ssl-keystore-password={{ .Values.clusterPassword }}
    {{- end }}
    ssl-truststore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/truststore.p12
    {{- if .Values.config.gemfire.embedded.tls.existingSecret }}
    ssl-truststore-password={{ .Values.config.gemfire.embedded.tls.password }}
    {{- else }}
    ssl-truststore-password={{ .Values.clusterPassword }}
    {{- end }}
    
{{ .Values.config.gemfire.embedded.tls.additionalProperties | indent 4 }}
    {{- end }}
    {{- if ( .Values.config.gemfire.embedded.auth.enabled) }}
    security-manager=com.l7tech.external.assertions.gemfire.BasicSecurityManager
    {{- if ( .Values.config.gemfire.embedded.auth.username) }}
    security-username={{ .Values.config.gemfire.embedded.auth.username }}
    {{- else }}
    security-username=default
    {{- end }}
    {{- if ( .Values.config.gemfire.embedded.auth.password )}}
    security-password={{ .Values.config.gemfire.embedded.auth.password }}
    {{- else }}
    security-password={{ .Values.clusterPassword }}
    {{- end }}
    {{- end }}
{{- end }}