{{- if .Values.config.gemfire  }}
{{- if .Values.config.gemfire.embedded.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-emb-gemfire-security-properties
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "-5"
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
stringData:
  gemfire_security: |+
    {{- if (.Values.config.gemfire.embedded.ssl.enabled) }}
    ssl-keystore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/gemfire-keystore
    ssl-keystore-password={{ .Values.config.gemfire.embedded.ssl.keystorePassword }}
    ssl-truststore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/gemfire-truststore
    ssl-truststore-password={{ .Values.config.gemfire.embedded.ssl.truststorePassword }}
{{ .Values.config.gemfire.embedded.ssl.additionalProperties | indent 4 }}
    {{- end }}
{{- end }}
{{- end }}