{{- if .Values.config.gemfire  }}
{{- if or (.Values.config.gemfire.embedded.auth.enabled) (.Values.config.gemfire.embedded.ssl.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-emb-gemfire-security-properties
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "-5"
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
stringData:
  gfsecurity: |+
    {{- if (.Values.config.gemfire.embedded.ssl.enabled) }}
    ssl-keystore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/gemfire-keystore
    ssl-keystore-password={{ .Values.config.gemfire.embedded.ssl.keystore.password }}
    ssl-truststore=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/gemfire-truststore
    ssl-truststore-password={{ .Values.config.gemfire.embedded.ssl.truststore.password }}
{{ .Values.config.gemfire.embedded.ssl.additionalProperties | indent 4 }}
    {{- end }}
    {{- if ( .Values.config.gemfire.embedded.auth.enabled) }}
    security-manager=com.l7tech.external.assertions.gemfire.BasicSecurityManager
    {{- if ( .Values.config.gemfire.embedded.auth.username) }}
    security-username={{ .Values.config.gemfire.embedded.auth.username }}
    {{- else }}
    security-username=default
    {{- end }}
    {{- if ( .Values.config.gemfire.embedded.auth.password )}}
    security-password={{ .Values.config.gemfire.embedded.auth.password }}
    {{- else }}
    security-password={{ .Values.clusterPassword }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}