{{- if and (eq (include "embedded.gemfire.enabled" .) "true") (empty .Values.config.gemfire.embedded.useExistingLocators) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-gemfire-locator
  labels:
    app: {{ template "gateway.name" . }}-gemfire-locator
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "-5"
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  revisionHistoryLimit: 10
  replicas: {{ .Values.config.gemfire.embedded.externalLocators.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-gemfire-locator
  serviceName: {{ $.Release.Name }}-gemfire-locator
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-gemfire-locator
        release: {{ .Release.Name }}
    {{- if  .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
    {{- end }}
    {{- if  .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-gemfire-locator
          image: {{ .Values.config.gemfire.embedded.externalLocators.image.registry }}/{{ .Values.config.gemfire.embedded.externalLocators.image.repository }}:{{ .Values.config.gemfire.embedded.externalLocators.image.tag }}
          imagePullPolicy: {{ .Values.config.gemfire.embedded.externalLocators.image.pullPolicy }}
          args: 
            - gfsh
            - start 
            - locator 
            - --name=$(POD_NAME) 
            - --hostname-for-clients=localhost
            - --J='-Dgemfire.jmx-manager-hostname-for-clients=localhost'
          {{- if .Values.config.gemfire.embedded.auth.enabled }}
            - --classpath=/gemfire/lib/layer7-gemfire-security.jar
          {{- end }}
          {{- if or (.Values.config.gemfire.embedded.auth.enabled) (.Values.config.gemfire.embedded.ssl.enabled) }}
            - --security-properties-file=/gemfire/config/gfsecurity.properties
          {{- end }}
            - --connect=false
            - --locators={{ template "embedded.gemfire.locators" $ }}
          env:
            - name: ACCEPT_TERMS
              value: {{ include "gemfire.acceptedTerms" . }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: "8"
              memory: 16384Mi
            requests:
              cpu: "1"
              memory: 1024Mi
          volumeMounts:
            - name: data
              mountPath: /data
        {{- if or (.Values.config.gemfire.embedded.auth.enabled) (.Values.config.gemfire.embedded.ssl.enabled) }}
            - name: {{ $.Release.Name }}-emb-gemfire-security-properties
              mountPath: /gemfire/config/gfsecurity.properties
              subPath: gfsecurity.properties
        {{- end }}
        {{- if .Values.config.gemfire.embedded.auth.enabled }}
            - name: {{ $.Release.Name }}-emb-gemfire-security-manager
              mountPath: /gemfire/lib/layer7-gemfire-security.jar
              subPath: layer7-gemfire-security.jar
        {{- end }}
        {{- if .Values.config.gemfire.embedded.ssl.enabled }}
            - name: {{ $.Release.Name }}-emb-gemfire-truststore
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/gemfire-truststore
              subPath: gemfire-truststore
            - name: {{ $.Release.Name }}-emb-gemfire-keystore
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/EmbeddedGemfireSharedStateProviderAssertion/gemfire-keystore
              subPath: gemfire-keystore
        {{- end }}
      volumes:
    {{- if or (.Values.config.gemfire.embedded.auth.enabled) (.Values.config.gemfire.embedded.ssl.enabled) }}
        - name: {{ $.Release.Name }}-emb-gemfire-security-properties
          secret:
            secretName: {{ $.Release.Name }}-emb-gemfire-security-properties
            items:
              - key: gfsecurity
                path: gfsecurity.properties
    {{- end }}
    {{- if .Values.config.gemfire.embedded.auth.enabled }}
        - name: {{ $.Release.Name }}-emb-gemfire-security-manager
          configMap:
            name: {{ $.Release.Name }}-emb-gemfire-security-manager-configmap
            items:
              - key: layer7-gemfire-security-jar
                path: layer7-gemfire-security.jar
    {{- end }}
    {{- if .Values.config.gemfire.embedded.ssl.enabled }}
        - name: {{ $.Release.Name }}-emb-gemfire-keystore
          secret:
            secretName: {{ .Values.config.gemfire.embedded.ssl.keystore.existingSecret }}
            items:
              - key: keystore
                path: gemfire-keystore
        - name: {{ $.Release.Name }}-emb-gemfire-truststore
          secret:
            secretName: {{ .Values.config.gemfire.embedded.ssl.truststore.existingSecret }}
            items:
              - key: truststore
                path: gemfire-truststore
    {{- end }}
{{- end }}