# Copyright (c) 2025 Broadcom Inc. and its subsidiaries. All Rights Reserved.
{{ if .Values.config.gemfire.embedded.externalLocators.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ template "gateway.chart" . }}-gmf-loc
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  name: {{ template "gateway.fullname" . }}-gmf-loc
  annotations:
    description: "Gemfire locator service"
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "-5"
{{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
spec:
  selector:
    app: {{ template "gateway.fullname" . }}-gmf-loc
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
    - protocol: TCP
      port: 10334
      targetPort: locator
      name: locator
      ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
      name: locator-metrics
      ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      name: locator-management-api
{{- end }}