{{- if .Values.config.gemfire  }}
{{/*{{- if or (.Values.config.gemfire.embedded.auth.enabled) (.Values.config.gemfire.embedded.tls.enabled) }}*/}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-client-cert
  namespace: yc683621
spec:
  duration: 21600h # 90d
  renewBefore: 3600h # 15d
  subject:
    organizations:
      - Example.com
  commonName: {{ $.Release.Name }}-client-cert
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.gemfireComponents"
  issuerRef:
    kind: ClusterIssuer
    name: gemfire-ca-issuer
    group: cert-manager.io
  secretName: {{ $.Release.Name }}-client-cert
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: {{ $.Release.Name }}-client-cert

{{/*{{- end }}*/}}
{{- end }}