{{- if and .Values.database.create (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-mysql-secret
  labels:
    app: {{ template "gateway.name" . }}-mysql
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/component: mysql
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- if or .Values.additionalAnnotations .Values.mysql.commonAnnotations (and .Values.otk.enabled .Values.otk.database.useDemoDb) }}
  {{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- range $key, $val := .Values.mysql.commonAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- if and .Values.otk.enabled .Values.otk.database.useDemoDb }}
    helm.sh/hook: pre-install,post-upgrade
    helm.sh/hook-weight: "-10"
  {{- end }}
  {{- end }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-database: {{ .Values.mysql.auth.database | b64enc | quote }}
  {{- if .Values.mysql.auth.username }}
  mysql-user: {{ .Values.mysql.auth.username | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}

