# Copyright (c) 2026 Broadcom Inc. and its subsidiaries. All Rights Reserved.
{{- if and (eq .Values.s3.enabled true) (eq .Values.s3.enableAuth true) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "seaweedfs-s3-secret" }}
{{- $access_key_admin := "" -}}
{{- $secret_key_admin := "" -}}
{{- $access_key_read := "" -}}
{{- $secret_key_read := "" -}}
{{- if $existingSecret }}
  {{- $access_key_admin = index $existingSecret.data "admin_access_key_id" | b64dec -}}
  {{- $secret_key_admin = index $existingSecret.data "admin_secret_access_key" | b64dec -}}
  {{- $access_key_read = index $existingSecret.data "read_access_key_id" | b64dec -}}
  {{- $secret_key_read = index $existingSecret.data "read_secret_access_key" | b64dec -}}
{{- else }}
  {{- $access_key_admin = randAlphaNum 10 -}}
  {{- $secret_key_admin = randAlphaNum 40 -}}
  {{- $access_key_read = randAlphaNum 10 -}}
  {{- $secret_key_read = randAlphaNum 40 -}}
{{- end }}
{{- if .Values.auth.access_key }}
  {{- $access_key_admin = .Values.auth.access_key -}}
{{- end }}
{{- if .Values.auth.secret_key }}
  {{- $secret_key_admin = .Values.auth.secret_key -}}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweedfs-s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: seaweedfs-s3
    chart: {{ template "seaweedfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  admin_access_key_id: {{ $access_key_admin }}
  admin_secret_access_key: {{ $secret_key_admin }}
  read_access_key_id: {{ $access_key_read }}
  read_secret_access_key: {{ $secret_key_read }}
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ $access_key_admin }}","secretKey":"{{ $secret_key_admin }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ $access_key_read }}","secretKey":"{{ $secret_key_read }}"}],"actions":["Read"]}]}'
  {{- if .Values.filer.s3.auditLogConfig }}
  filer_s3_auditLogConfig.json: |
    {{ toJson .Values.filer.s3.auditLogConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.s3.auditLogConfig }}
  s3_auditLogConfig.json: |
    {{ toJson .Values.s3.auditLogConfig | nindent 4 }}
  {{- end }}
{{- end }}
