{{- if and (eq .Values.s3.enabled true ) (eq .Values.s3.enableAuth true) }}
{{- $access_key_admin := randAlphaNum 10 -}}
{{- $secret_key_admin := randAlphaNum 40 -}}
{{- $access_key_read := randAlphaNum 10 }}
{{- $secret_key_read := randAlphaNum 40 }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweedfs-s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: seaweedfs-s3
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
{{if .Values.auth.access_key }}
  {{- $access_key_admin := .Values.auth.access_key }}
  admin_access_key_id: {{ $access_key_admin }}
  read_access_key_id: {{ $access_key_read }}
{{ else }}
  admin_access_key_id: {{ $access_key_admin }}
  read_access_key_id: {{ $access_key_read }}
{{ end }}
{{if .Values.auth.secret_key }}
  {{- $secret_key_admin := .Values.auth.secret_key }}
  admin_secret_access_key: {{ $secret_key_admin }}
  read_secret_access_key: {{ $secret_key_read }}
{{ else }}
  admin_secret_access_key: {{ $secret_key_admin }}
  read_secret_access_key: {{ $secret_key_read }}
{{ end }}
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ $access_key_admin }}","secretKey":"{{ $secret_key_admin }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ $access_key_read }}","secretKey":"{{ $secret_key_read }}"}],"actions":["Read"]}]}'
  {{- if .Values.filer.s3.auditLogConfig }}
  filer_s3_auditLogConfig.json: |
    {{ toJson .Values.filer.s3.auditLogConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.s3.auditLogConfig }}
  s3_auditLogConfig.json: |
    {{ toJson .Values.s3.auditLogConfig | nindent 4 }}
  {{- end }}
{{- end }}