# Analytics stack configuration - Apache Druid
# This Chart is designed to be deployed as a SubChart of the
# Broadcom API Developer Portal

# Global values
global:
  portalRepository: caapim/
  pullSecret: broadcom-apim
  # these default to mysql settings above, change if connecting to an external database.
# setupDemoDatabase: true
  databaseType: mysql
  databaseHost: mysql
  databasePort: 3306
  databaseUseSSL: true
  databaseRequireSSL: false
  databaseUsername: admin
  databaseSecret:
  subdomainPrefix: dev-portal
  legacyHostnames: false
  legacyDatabaseNames: false
# databasePassword: 7layer
  deepStorage:
    auth:
      secretName: seaweedfs-s3-secret

image:
    seaweedfs: seaweedfs:5.3.3
    migrationUtility: seaweedfs:5.3.3
persistence:
    storage:
      seaweedfs: 50Gi


migrateData: false
imageOverride: null
restartPolicy: Always
imagePullPolicy: Always
loggingLevel: 1
replicaCount: 1
clusterDomain: cluster.local
minio:
    bucketName: api-metrics
forceRedeploy: true
nameOverride: seaweedfs-s3
serviceAccount:
  create: true
# Core configuration
idleTimeout: 30  # Connection idle seconds
dataCenter: ""  # Current volume server's data center name
rack: ""  # Current volume server's rack name
whiteList: ""  # Comma separated IP addresses having write permission
disableHttp: false  # Disable HTTP requests, only gRPC operations are allowed
metricsPort: 9324  # Prometheus metrics listen port
metricsIp: ""  # Metrics listen IP. If empty, defaults to bindAddress
loggingOverrideLevel: null  # Override logging level
auth:
  secretName: seaweedfs-s3-secret
# Leave access_key and secret_key empty to auto-generate values.
# access_key:
# secret_key:
  # admin_access_key_id:
  # admin_secret_access_key:
  # read_access_key_id:
  # read_secret_access_key:
# Service configuration
s3:
  enabled: true  # Whether to enable S3 gateway
  port: 8333
  enableAuth: true
  existingConfigSecret: seaweedfs-s3-secret
sftp:
  enabled: false  # Whether to enable SFTP server
filer:
  port: 8888
  grpcPort: 18888
  defaultReplicaPlacement: "000"
  dirListLimit: 100000
  s3:
    enableAuth: true
    createBuckets:
      - name: api-metrics
        anonymousRead: false
      - name: file-storage
        anonymousRead: false
  config: |
    [leveldb2]
    enabled = false
volume:
  port: 8080
  grpcPort: 18080
  compactionMBps: 50
  minFreeSpacePercent: 7
  dataDirs:
    - name: data-0
      type: "persistentVolumeClaim"
      size: "50Gi"
      maxVolumes: 50
master:
  port: 9333
  grpcPort: 19333
  config: ""
  volumeSizeLimitMB: 1024
# Service settings
service:
  annotations: {}  # Annotations for the service
  type: ClusterIP  # Service type (ClusterIP, NodePort, LoadBalancer)
# Storage configuration
data:
  type: "emptyDir"  # Options: "hostPath", "persistentVolumeClaim", "emptyDir"
  hostPathPrefix: /mnt/data  # Path prefix for hostPath volumes
  claimName: seaweedfs-data-pvc  # Name of the PVC to use
  size: ""  # Size of the PVC
  storageClass: ""  # Storage class for the PVC
# Health checks
readinessProbe:
  enabled: true
  httpGet:
    path: /cluster/status
    port: 9333
  scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 40
  successThreshold: 1
  failureThreshold: 6
  timeoutSeconds: 40
livenessProbe:
  enabled: true
  httpGet:
    path: /cluster/status
    port: 9333
  scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 40
  successThreshold: 1
  failureThreshold: 6
  timeoutSeconds: 40
# Enable if replica count > 1
startupProbe:
  enabled: false
  httpGet:
    path: /cluster/status
    port: 9333
  scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 15
  timeoutSeconds: 40
# Additional resources
extraEnvironmentVars: {}  # Additional environment variables
extraVolumeMounts: ""  # Additional volume mounts
extraVolumes: ""  # Additional volumes
initContainers: ""  # Init containers
sidecars: ""  # Sidecar containers
annotations: {}  # Annotations for the deployment
podAnnotations: {}  # Annotations for the pods
podLabels: {}  # Labels for the pods
# Scheduling configuration
# Affinity Settings
# Commenting out or setting as empty the affinity variable, will allow
# deployment to single node services such as Minikube
# affinity: |
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchLabels:
#             app.kubernetes.io/name: seaweedfs"
#             app.kubernetes.io/instance: {{ .Release.Name }}
#             app.kubernetes.io/component: master
#         topologyKey: kubernetes.io/hostname
# Topology Spread Constraints Settings
# This should map directly to the value of the topologySpreadConstraints
# for a PodSpec. By Default no constraints are set.
topologySpreadConstraints: ""
# Toleration Settings for master pods
# This should be a multi-line string matching the Toleration array
# in a PodSpec.
tolerations: ""
# nodeSelector labels for master pod assignment, formatted as a muli-line string.
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: |
  kubernetes.io/arch: amd64
# Used to assign priority to master pods
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
priorityClassName: ""
# Used to assign a service account.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccountName: ""
# Configure security context for Pod
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
# Example:
podSecurityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
# podSecurityContext: {}
# Configure security context for Container
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
# Example:
# containerSecurityContext:
#   enabled: true
#   runAsUser: 2000
#   allowPrivilegeEscalation: false
containerSecurityContext: {}
# Resource management
resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
