apiVersion: v1
kind: Secret
metadata:
  name: minio-secret  
  labels:
    app: minio    
type: Opaque
stringData:
  #These values are for reference. Change the below values as per the convenience.
  MINIO_ACCESS_KEY: "userDefinedAccessKey"
  MINIO_SECRET_KEY: "userDefinedSecretKey"