{{- if and .Values.config.redis.subChart.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-redis-secret
  labels:
    app: {{ template "gateway.name" . }}-redis
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- if or .Values.additionalAnnotations .Values.redis.commonAnnotations }}
  {{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- range $key, $val := .Values.redis.commonAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.redis.auth.username }}
  redis-username: {{ .Values.redis.auth.username | b64enc | quote }}
  {{- end }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}

