{{- if .Values.config.redis.subChart.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gateway.fullname" . }}-redis
  labels:
    app: {{ template "gateway.name" . }}-redis
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- if or .Values.additionalAnnotations .Values.redis.commonAnnotations .Values.redis.service.annotations }}
  {{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- range $key, $val := .Values.redis.commonAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- range $key, $val := .Values.redis.service.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.redis.service.type | default "ClusterIP" }}
  ports:
  - name: redis
    port: {{ .Values.redis.service.port | default 6379 }}
    targetPort: redis
    protocol: TCP
  selector:
    app: {{ template "gateway.fullname" . }}-redis
    release: {{ .Release.Name }}
    app.kubernetes.io/component: redis
{{- end }}

