apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
  namespace: {{ .Release.Namespace }}
  labels:
    app: seaweedfs
    component: filer
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: "swfs-filer"
    port: {{ .Values.filer.port }}
    targetPort: {{ .Values.filer.port }}
    protocol: TCP
  - name: "swfs-filer-grpc"
    port: {{ .Values.filer.grpcPort }}
    targetPort: {{ .Values.filer.grpcPort }}
    protocol: TCP
  selector:
    app: seaweedfs
    component: filer
