{{- if and (or (eq .Values.seaweedfs.s3.enabled true) (eq .Values.seaweedfs.enabled true )) (eq .Values.seaweedfs.s3.enableAuth true) }}
{{- $access_key_admin := .Values.minio.auth.access_key -}}
{{- $secret_key_admin := .Values.minio.auth.secret_key -}}
{{- $access_key_read := randAlphaNum 10 }}
{{- $secret_key_read := randAlphaNum 40 }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweedfs-s3-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: s3
stringData:
  admin_access_key_id: {{ .Values.minio.auth.access_key }}
  admin_secret_access_key: {{ .Values.minio.auth.secret_key }}
  read_access_key_id: {{ randAlphaNum 10 | b64enc }}
  read_secret_access_key: {{ randAlphaNum 40 | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.access_key  }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.secret_key }} 
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ $access_key_admin }}","secretKey":"{{ $secret_key_admin }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ $access_key_read }}","secretKey":"{{ $secret_key_read }}"}],"actions":["Read"]}]}'
  {{- if .Values.seaweedfs.filer.s3.auditLogConfig }}
  filer_s3_auditLogConfig.json: |
    {{ toJson .Values.seaweedfs.filer.s3.auditLogConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.seaweedfs.s3.auditLogConfig }}
  s3_auditLogConfig.json: |
    {{ toJson .Values.seaweedfs.s3.auditLogConfig | nindent 4 }}
  {{- end }}
{{- end }}