apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: {{ .Values.minio.port | quote }}
    port: {{ .Values.minio.port }}
    targetPort: 9000
  selector:
    app: minio
  sessionAffinity: ClientIP