apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.rabbitmq.auth.secretName}}
  annotations:
    helm.sh/hook: pre-install
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{if .Values.rabbitmq.auth.password }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
{{ else }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
{{if .Values.rabbitmq.auth.erlangCookie }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc | quote }}
{{ else }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}