apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.rabbitmq.loadDefinition.existingSecret}}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  load_definition.json: |
    {
      "policies": [
        {
          "vhost": "/",
          "name": "rabbitmq-ha",
          "pattern": ".",
          "apply-to": "all",
          "definition": { "ha-mode": "all", "ha-sync-mode": "automatic" },
          "priority": 0
        }
      ],
      "exchanges": [
        {
          "name": "portal-external",
          "vhost": "/",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "portal-internal",
          "vhost": "/",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ]
    }