apiVersion: v1
kind: Service
metadata:
  name: analytics-server
  labels:
    app: analytics-server
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if  .Values.global.additionalAnnotations }}
  annotations:
  {{- range $key, $val := .Values.global.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}  
spec:
  ports:
    - port: 9045
      targetPort: 9045
      name: analytics-server
  selector:
    app: analytics-server
  type: ClusterIP
  sessionAffinity: ClientIP