apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    app: kafka