apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  SERVICE_NAME: kafka
  KAFKA_PORT: "9092"
  KAFKA_ZOOKEEPER_CONNECT: {{.Values.zookeeper.hostname}}:{{.Values.zookeeper.port}}
  KAFKA_ADVERTISED_HOST_NAME: kafka
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
  KAFKA_LISTENERS: PLAINTEXT://:9092
  BROKER_ID_COMMAND: echo $HOSTNAME | rev | cut -d "-" -f 1 