{{- if and .Values.serviceAccount.create .Values.rbac.create (not .Values.global.serviceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "portal.fullname" . }}-batch-reader
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "portal.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "portal.fullname" . }}-batch-reader
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}