apiVersion: v1
kind: Secret
metadata:
  name: portal-enterprise-secret
  labels:
    app: portal-enterprise
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ENTERPRISE_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  RBAC_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}
  SEARCH_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}