{{ if .Values.portalEnterprise.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: portal-enterprise
  {{- if  .Values.global.additionalAnnotations }}
  annotations:
  {{- range $key, $val := .Values.global.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}  
  name: portal-enterprise-pdb
spec:
  {{- if .Values.portalEnterprise.pdb.minAvailable }}
  minAvailable: {{ .Values.portalEnterprise.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.portalEnterprise.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.portalEnterprise.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: portal-enterprise
{{ end }}
