{{if not .Values.security.mongodb.useExistingSectet }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    chart: {{ template "intelligence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mongodb-passwords: {{ required "Please fill in security.mongodb.dbPassword in values.yaml" .Values.security.mongodb.dbPassword | b64enc | quote }}
  mongodb-root-password: {{ required "Please fill in security.mongodb.rootPassword in values.yaml" .Values.security.mongodb.rootPassword | b64enc | quote }}
{{- end }}