apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "gateway.name" . }}-otk-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}
