{{- if or (.Values.config.gemfire.embedded.enabled) (.Values.config.gemfire.external.enabled)}}
{{- if and (.Values.config.gemfire.tls.enabled) (not .Values.config.gemfire.tls.existingSecret)}}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-gemfire-tls-cert
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  {{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.config.gemfire.tls.password }}
  password: {{ .Values.config.gemfire.tls.password }}
  {{- else }}
  password: {{ .Values.clusterPassword }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}