{{- if or (.Values.config.gemfire.embedded.enabled) (.Values.config.gemfire.external.enabled) }}
{{- if and (.Values.config.gemfire.tls.enabled) (not .Values.config.gemfire.tls.existingSecret) }}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-gemfire-tls-cert
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ template "gateway.name" . }}.com
  commonName: {{ $.Release.Name }}-gemfire-tls-cert
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ $.Release.Name }}-gemfire-gateway
  issuerRef:
    kind: {{ .Values.config.gemfire.tls.certificate.issuerRef.kind }}
    name: {{ .Values.config.gemfire.tls.certificate.issuerRef.name }}
    group: cert-manager.io
  secretName: {{ $.Release.Name }}-gemfire-tls-cert
  secretTemplate:
    labels:
      app: {{ template "gateway.name" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      {{- range $key, $val := .Values.additionalLabels }}
      {{ $key }}: "{{ $val }}"
      {{- end }}
    {{- if  .Values.additionalAnnotations }}
    annotations:
      "helm.sh/hook": pre-install
      "helm.sh/hook-weight": "-4"
    {{- range $key, $val := .Values.additionalAnnotations }}
      {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- end }}
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: {{ $.Release.Name }}-gemfire-tls-cert
{{- end }}
{{- end }}
{{- end }}