# Copyright (c) 2025 Broadcom Inc. and its subsidiaries. All Rights Reserved.
{{ if .Values.config.gemfire.managementConsole.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ template "gateway.chart" . }}-gmf-mc
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  name: {{ template "gateway.fullname" . }}-gmf-mc
  annotations:
    description: "Gemfire management console service"
{{- range $key, $val := .Values.config.gemfire.managementConsole.service.annotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
spec:
  selector:
    app: {{ template "gateway.fullname" . }}-gmf-mc
    release: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.config.gemfire.managementConsole.service.port }}
      targetPort: {{ .Values.config.gemfire.managementConsole.service.port }}
      name: http
{{- end }}