{{- if .Values.ingress.type.openshift }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apim-route
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "default-tenant-host" . | quote }}
  port:
    targetPort: portal-https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: dispatcher
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pssg-enroll
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "pssg-enroll-host" . | quote }}
  port:
    targetPort: tssg-enroll
  tls:
    termination: passthrough
  to:
    kind: Service
    name: apim
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pssg-sync
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "pssg-sync-host" . | quote }}
  port:
    targetPort: tssg-sync
  tls:
    termination: passthrough
  to:
    kind: Service
    name: apim
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apim-route-broker
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "broker-host" . | quote }}
  port:
    targetPort: {{ printf "%s-broker" .Values.portal.defaultTenantId | quote }}
  tls:
    termination: passthrough
  to:
    kind: Service
    name: apim
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apim-route-sso
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "pssg-sso-host" . | quote }}
  port:
    targetPort: {{ printf "%s-sso" .Values.portal.defaultTenantId | quote }}
  tls:
    termination: passthrough
  to:
    kind: Service
    name: apim
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apim-route-tssg
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "tssg-public-host" . | quote }}
  port:
    targetPort: {{ printf "%s-https" .Values.portal.defaultTenantId | quote }}
  tls:
    termination: passthrough
  to:
    kind: Service
    name: apim
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: datalake-analytics
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: {{ include "analytics-host" . | quote }}
  port:
    targetPort: {{ printf "%s-datalake" .Values.portal.defaultTenantId | quote }}
  tls:
    termination: passthrough
  to:
    kind: Service
    name: apim
    weight: 100
  wildcardPolicy: None
{{- range .Values.ingress.customRoutes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .subdomain }}-route
  labels:
    app: {{ template "portal.name" $ }}
    chart: {{ template "portal.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    {{- range $key, $val := $.Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := $.Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := $.Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: "{{ .subdomain }}.{{ $.Values.portal.domain }}"
  port:
    targetPort: {{ .service.port }}
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .service.name }}
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- range .Values.ingress.tenantIds }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ . }}-route
  labels:
    app: {{ template "portal.name" $ }}
    chart: {{ template "portal.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    {{- range $key, $val := $.Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := $.Values.ingress.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  annotations:
  {{- range $key, $val := $.Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  host: "{{ . }}.{{ $.Values.portal.domain }}"
  port:
    targetPort: portal-https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: dispatcher
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}
