name: Execute Unit Tests

on:
  pull_request:
    branches:
      - stable
      - develop/gateway
      - develop/portal
jobs:
  kubeconform-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.0.0
        with:
          version: v3.13.3
      - name: Run kubeconform
        run: .github/unittests.sh
