name: Lint and Test Charts

on:
  pull_request:
    branches:
      - stable
      - develop/gateway
      - develop/portal
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Helm
        uses: azure/setup-helm@v5.0.0
        with:
          version: v3.13.3
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
      - name: Run chart-testing (lint)
        # Version increment check is enforced only for stable, as that branch is customer-facing
        run: ct lint --config .github/ct-lint.yaml --check-version-increment ${{ github.base_ref == 'stable' }} --target-branch ${{ github.base_ref }}
      - name: Run version-check
        # Version check is only required for stable since it is the branch exposed to customers
        if: github.base_ref == 'stable'
        run: .github/version-check.sh