name: Lint and Test Charts

on:
  pull_request:
    branches:
      - stable
      - develop/gateway
      - develop/portal
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Helm
        uses: azure/setup-helm@v4.0.0
        with:
          version: v3.13.3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch stable)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct-lint.yaml --check-version-increment true --target-branch stable
      - name: Run version-check
        run: .github/version-check.sh