apiVersion: v2
appVersion: "5.4"
description: Apache Kafka Chart for Broadcom APIM
home: https://github.com/CAAPIM/apim-charts
maintainers:
- name: Gazza7205
name: kafka
sources:
- https://github.com/CAAPIM/apim-charts
type: application
version: 1.2.5
